spring:
  datasource:
    url: ENC(Uhr3Sbmbw6S4Cfne8uoonliruTpk+tTLucrJQsp8Gjf7tdheEtJJaYJ27stSsQArFt21Dno14ekP/kFCM5SLUIOeybyNBuLbZ6oCUHfzK6TkPyZcJ7RHHwObq8dWwwrdtaqgnwbS/tM=)
    username: ENC(zfsBcyn8ZVDvxlCDTytkkA==)
    password: ENC(Ks5Qju3bX6hdIsrhfnCC2/KRoKRhMGdT)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379


jasypt:
  encryptor:
    bean : jasyptStringEncryptor
